### ISSUE TITLE
undefined is not a function error on shutdown

### ISSUE THREAD

**Issue by msamblanet** [brycebaril/stream-file-archive#1]
With 1.1.1, I am seeing the stack trace below on shutdown:

```
TypeError: undefined is not a function
    at process.<anonymous> (C:\\pombe\\v2\\v2\\lib\\util\\node_modules\\stream-file-archive\\index.js:70:42)
    at process.emit (events.js:104:17)
    at Signal.wrap.onsignal (node.js:655:46)
```

Based on a quick scan of the code, the [on-sughup handler at index.js line 70](https://github.com/brycebaril/stream-file-archive/blob/v1.1.1/index.js#L70) is referencing "this".  It either needs to reference a self out of a closure or have the handler bound to this...

```
process.on("SIGHUP", function () {this.renew(true)}.bind(this));
```

**Comment by brycebaril** [comment]
Fixed, thanks!
